apiVersion: v1
kind: Pod
metadata:
  name: pod-02
spec:
  containers:
    - name: app
      image: gcr.io/distroless/python3-debian11
      command:
        - python
        - -m
        - http.server
        - '8080'

