apiVersion: v1
kind: Pod
metadata:
   name: pod -09
   labels:
     appName: nginx
spec:
  containers:
    -name: nginx
    image: nginx

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    appName: nginx
ports:
 - name: http
   protocols: TCP
   port: 80
   targetPort: 9376