apiVersion: v1
kind: Pod
metadata:
  name: pod-07
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-path
          mountPath: /usr/share/nginx/html
initContainers:
  - name: nginx-content
    image: rkalluru/78-nginx:v2
    volumeMounts:
      - name: nginx-path
        mountPath: /usr/share/nginx/html
volumes:
  - name: nginx-path
    emptyDir: {}