apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: frontend
      image: 058264231458.dkr.ecr.us-east-1.amazonaws.com/expense-frontend:latest

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    appName: backend
    projectName: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80